config/routes.rb
Rails.application.routes.draw do
  get 'chats/show'
  get 'relationships/followings'
  get 'relationships/followers'
  devise_for :users
  root 'homes#top'
  get 'home/about' => 'homes#about'
  
  # ネストさせる
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    get "search", to: "users#search"
  end
  
  resources :books do
    resource :favorites, only: [:create, :destroy]
  	resources :book_comments, only: [:create, :destroy]
  end
  get "searches" => "searches#search"
  get 'chat/:id', to: 'chats#show', as: 'chat'
  resources :chats, only: [:create]
  resources :groups do
  get "join" => "groups#join"
  get "new/mail" => "groups#new_mail"
  get "send/mail" => "groups#send_mail"
  get "search", to: "groups#search"
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, uniqueness: true, presence: true, length: { minimum: 2, maximum: 20}
  validates :introduction, length: { maximum: 50 }

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :user_rooms, dependent: :destroy
  has_many :chats, dependent: :destroy
  has_many :view_counts, dependent: :destroy
  has_many :group_users
  has_many :groups, through: :group_users
  attachment :profile_image, destroy: false
  
  # フォローをした、されたの関係
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  
  # 一覧画面で使う
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower
  
  # フォローしたときの処理
def follow(user_id)
  relationships.create(followed_id: user_id)
end
# フォローを外すときの処理
def unfollow(user_id)
  relationships.find_by(followed_id: user_id).destroy
end

# フォローしているか判定
def following?(user)
  followings.include?(user)
end

def User.search(search, model, how)
    if model == "user"
      if how == "partical"
        User.where("name LIKE ?", "%#{search}%")
      elsif how == "forward"
        User.where("name LIKE ?", "#{search}%")
      elsif how == "backward"
        User.where("name LIKE?", "%#{search}")
      elsif how == "match"
        User.where("name LIKE?", "#{search}")
      end
    end
end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:update]

  def show
    @user = User.find(params[:id])
    @books = Book.where(user_id: @user.id)
    @book = Book.new
    @today_book = @books.created_today
    @this_week_book = @books.created_this_week
    @last_week_book = @books.created_last_week
  end

  def index
    @user = current_user
    @users = User.all
    @book = Book.new
    @books = Book.all
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
        render "edit"
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice]="You have updated user successfully."
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end
  
  def search
    @user = User.find(params[:user_id])
    @books = @user.books 
    @book = Book.new
    if params[:created_at] == ""
      @search_book = "日付を選択してください"#①
    else
      create_at = params[:created_at]
      @search_book = @books.where(['created_at LIKE ? ', "#{create_at}%"]).count#②
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_count.html.erb
 <h2>投稿数の前日比・先週比</h2>
 <table class="table">
  <thead>
  <tr>
   <th>今日の投稿</th>
   <th>昨日の投稿</th>
   <th>前日比</th>
  </tr>
  </thead>
   <tbody>
    <tr>
     <td><%= @today_book.count %></td>
     <td><%= @books.created_days_ago(1).count %></td>
     <% if @books.created_days_ago(1).count == 0 %>
     <td>前日の投稿はなし</td>
     <% else %>
       　<td><% @the_day_before =   @today_book.count / @books.created_days_ago(1).count.to_f  %>
       　<%= (@the_day_before * 100).round %>%</td>
     <% end %>
     </tr>
   </tbody>
  </table>


  <table class="table">
  <thead>
  <tr>
   <th>今週の投稿</th>
   <th>先週の投稿</th>
   <th>比</th>
  </tr>
  </thead>
   <tbody>
    <tr>
     <td><%= @this_week_book.count %></td>
     <td><%= @last_week_book.count %></td>
     <% if @last_week_book.count == 0 %>
     <td>先週の投稿はなし</td>
     <% else %>
       　<td><% @the_week_before =   @this_week_book.count / @last_week_book.count.to_f  %>
       　<%= (@the_week_before * 100).round %>%</td>
     <% end %>
     </tr>
   </tbody>
  </table>
  <h2>7日分の投稿数</h2>
  <table class="table">
   <thead>
    <tr>
     <th>６日前</th>
     <th>5日前</th>
     <th>4日前</th>
     <th>3日前</th>
     <th>２日前</th>
     <th>昨日</th>
     <th>今日</th>
    </tr>
   </thead>
   <tbody>
    <tr>
     <th><%= @books.created_days_ago(6).count %></th>
     <th><%= @books.created_days_ago(5).count %></th>
     <th><%= @books.created_days_ago(4).count %></th>
     <th><%= @books.created_days_ago(3).count %></th>
     <th><%= @books.created_days_ago(2).count %></th>
     <th><%= @books.created_days_ago(1).count %></th>
     <th><%= @today_book.count %></th>
    </tr>
   </tbody>
  </table>
  
  <canvas id="myChart" width="300" height="100"> </canvas>
    <script> 
    var ctx = document.getElementById("myChart").getContext('2d');
    var myChart = new Chart(ctx, {
        type: 'line',                      
        data: {
            labels: ['6日前', '5日前', '4日前', '3日前', '2日前', '1日前', '今日'],
            datasets: [{
                label: "投稿数",
                data: [<%= @books.created_days_ago(6).count %>, <%= @books.created_days_ago(5).count %>, <%= @books.created_days_ago(4).count %>, <%= @books.created_days_ago(3).count %>, <%= @books.created_days_ago(2).count %>, <%= @books.created_days_ago(1).count %>, <%= @today_book.count%>],
                backgroundColor: 'rgba(255, 80, 120, 1.0)',
                borderColor: 'rgba(255, 80, 120, 1.0)',
                fill: false
            }]
        },
    });
</script>

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
        <td><%= user.name %></td>
      <% if current_user != user %>
        <td><% if current_user.following?(user) %>
          <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
          <% else %>
          <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
        <% end %></td>
      <% end %>
        <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= form_with url: user_search_path(@user), method: :get do |f| %>
  <%= f.date_field :created_at %>
  <%= f.submit '検索', class: 'btn btn-primary'  %>
<% end %>

<div id="search_result">
  <% if @search_book.present? %>
    <%= render 'search', search_book: @search_book %>
  <% end %>
</div>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= attachment_image_tag(@user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  
      <tr>
      <th>follows</th>
      <td>
        <%= link_to user_followings_path(user) do %>
          <%= user.followings.count %>
        <% end %>
      </td>
    </tr>
    <tr>
      <th>followers</th>
      <td>
        <%= link_to user_followers_path(user) do %>
          <%= user.followers.count %></td>
        <% end %>
      </tr>
</table>
        <% if current_user != user %>
        <td>
          <% if current_user.following?(user) %>
          <tr>
          <td><%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %></td>
          <td><% if current_user != @user %>
          <%= link_to 'チャットを始める', chat_path(@user.id) %>
          <% end %>   
          </td>
          </tr>
          <% else %>
          <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
        <% end %>
        </td>
        <% end %>
<div class='row'>
  <%= link_to edit_user_path(user) ,class: "btn btn-outline-secondary btn-block fas fa-user-cog" do %>
  <% end %>
  
</div>

app/views/users/_search.html.erb
<h4>検索結果</h4>
  <table class='table table-bordered'>
    <thead>
      <tr> 
        <th>投稿数</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= search_book %></td>
      </tr>
    </tbody>
  </table>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.attachment_field :profile_image, class: "form-control-file user_image" %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit 'Update User', class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
    <div class='row'>
    <div class='col-md-3'>
<h2>User info</h2>
<%= render 'info', user: current_user %>
<h2 class="mt-3">New book</h2>
<%= render 'books/form', book: @book %>
</div>
    <div class='col-md-8 offset-md-1'>
<h2>Users</h2>
<%= link_to "グループを作成する", new_group_path %> | 
<%= link_to "グループ一覧", groups_path %>
<%= render 'index',users: @users %>
</div>
  </div>
</div>

app/views/users/search.js.erb
$("#search_result").html("<%= j(render 'search', search_book: @search_book) %>");

app/views/users/show.html.erb
<main>
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book:@book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books:@books %>
      <%= render 'count',book:@books %>
    </div>
  </div>
</div>
</main>